language: python
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
# command to install dependencies
install:
  - "pip install ."
  - "pip install mock"
  - "pip install coveralls"
  - "pip install codecov"
  - "pip install -r requirements.txt"
  - "pip install smpplib"
# split the test run according to
# http://blog.travis-ci.com/2012-11-28-speeding-up-your-tests-by-parallelizing-them/
env:
  global:
    - PYTHONHASHSEED=random
  matrix:
    - TESTS=tests/
matrix:
    allow_failures:
       - python: 3.4
       - python: 3.5
       - python: 3.6
# command to run tests
script: "nosetests -v --with-coverage --cover-package=privacyidea $TESTS"

after_success: 
    - codecov

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aeb7493dbe5c478e6c2b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
